UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Things Fall Apart' AND author_last ILIKE 'Achebe' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Watership Down' AND author_last ILIKE 'Adams' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 2 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Clan of the Cave Bear' AND author_last ILIKE 'Auel' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Fahrenheit 451' AND author_last ILIKE 'Bradbury' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Boys in the Boat' AND author_last ILIKE 'Brown' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Bury My Heart at Wounded Knee' AND author_last ILIKE 'Brown' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 2 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Parable of the Sower' AND author_last ILIKE 'Butler' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 2 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Parable of the Talents' AND author_last ILIKE 'Butler' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Alienist' AND author_last ILIKE 'Carr' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 2 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Power of One' AND author_last ILIKE 'Courtenoy' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Passage' AND author_last ILIKE 'Cronin' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Twelve' AND author_last ILIKE 'Cronin' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The City of Mirrors' AND author_last ILIKE 'Cronin' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Complete Sherlock Holmes' AND author_last ILIKE 'Doyle' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 2 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Joys of Motherhood' AND author_last ILIKE 'Emecheta' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'James' AND author_last ILIKE 'Everett' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Time After Time' AND author_last ILIKE 'Finney' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Likeness' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Faithful Place' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Broken Harbor' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Searcher' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Secret Place' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Trespasser' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Witch Elm' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Hunter' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Keeper' AND author_last ILIKE 'French' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'From Beirut to Jerusalem' AND author_last ILIKE 'Friedman' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Forever' AND author_last ILIKE 'Hamill' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Snow in August' AND author_last ILIKE 'Hamill' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Great Alone' AND author_last ILIKE 'Hannah' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 2 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'A Thousand Splendid Suns' AND author_last ILIKE 'Hosseini' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Kite Runner' AND author_last ILIKE 'Hosseini' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Never Let Me Go' AND author_last ILIKE 'Ishiguro' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Say Nothing' AND author_last ILIKE 'Keefe' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Stand' AND author_last ILIKE 'King' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Poisonwood Bible' AND author_last ILIKE 'Kingsolver' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Devil in the White City' AND author_last ILIKE 'Larson' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Girl Who Played with Fire' AND author_last ILIKE 'Larsson' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Girl with the Dragon Tatoo' AND author_last ILIKE 'Larsson' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Girl Who Kicked the Hornet''s Nest' AND author_last ILIKE 'Larsson' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'To Kill A Mockingbird' AND author_last ILIKE 'Lee' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Glory and the Dream' AND author_last ILIKE 'Manchester' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Matterhorn' AND author_last ILIKE 'Marlantes' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Truman' AND author_last ILIKE 'McCullough' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Source' AND author_last ILIKE 'Michener' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Last Days of Ptolemy Grey' AND author_last ILIKE 'Mosely' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Eight' AND author_last ILIKE 'Neville' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE '"Cry' AND author_last ILIKE 'Paton' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Chosen' AND author_last ILIKE 'Potok' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Promise' AND author_last ILIKE 'Potok' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Black and Blue' AND author_last ILIKE 'Quindlin' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Rise and Fall of the Third Reich' AND author_last ILIKE 'Shier' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'One Day in the Life of Ivan Denisovich' AND author_last ILIKE 'Solzhenitsyn' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 3 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'Grapes of Wrath' AND author_last ILIKE 'Steinbeck' LIMIT 1) AND rating IS NULL;
UPDATE public.user_books SET rating = 1 WHERE book_id = (SELECT id FROM public.books WHERE title ILIKE 'The Hobbit' AND author_last ILIKE 'Tolkien' LIMIT 1) AND rating IS NULL;
