-- Sal's Library import: 892 books
-- Run this in the Supabase SQL editor

ALTER TABLE books ADD CONSTRAINT books_title_author_last_key UNIQUE (title, author_last);

INSERT INTO books (title, author_first, author_last, series, series_num) VALUES
  ('Adrenaline', 'Jeff', 'Abbott', 'Sam Capra', '1'),
  ('The Last Minute', 'Jeff', 'Abbott', 'Sam Capra', '2'),
  ('Downfall', 'Jeff', 'Abbott', 'Sam Capra', '3'),
  ('Panic', 'Jeff', 'Abbott', NULL, NULL),
  ('Inside Man', 'Jeff', 'Abbott', 'Sam Capra', '4'),
  ('The First Order', 'Jeff', 'Abbott', 'Sam Capra', '5'),
  ('Blame', 'Jeff', 'Abbott', NULL, NULL),
  ('The Three Beths', 'Jeff', 'Abbott', NULL, NULL),
  ('Things Fall Apart', 'Chinua', 'Achebe', NULL, NULL),
  ('Watership Down', 'Richard', 'Adams', NULL, NULL),
  ('Tuesdays with Morrie', 'Mitch', 'Albom', NULL, NULL),
  ('D-Day', 'Stephen', 'Ambrose', NULL, NULL),
  ('Band of Brothers', 'Stephen', 'Ambrose', NULL, NULL),
  ('A Prisoner of Birth', 'Jeffrey', 'Archer', NULL, NULL),
  ('Kane and Abel', 'Jeffrey', 'Archer', NULL, NULL),
  ('Paths of Glory', 'Jeffrey', 'Archer', NULL, NULL),
  ('The Prodigal Daughter', 'Jeffrey', 'Archer', NULL, NULL),
  ('The Foundation Trilogy', 'Isaac', 'Asimov', NULL, NULL),
  ('Handmaid''s Tale', 'Margaret', 'Atwood', NULL, NULL),
  ('The Testaments', 'Margaret', 'Atwood', NULL, NULL),
  ('Clan of the Cave Bear', 'Jean', 'Auel', NULL, NULL),
  ('The Mammoth Hunters', 'Jean', 'Auel', NULL, NULL),
  ('The Plains of Passage', 'Jean', 'Auel', NULL, NULL),
  ('The Shelters of Stone', 'Jean', 'Auel', NULL, NULL),
  ('The Valley of Horses', 'Jean', 'Auel', NULL, NULL),
  ('Where the Truth Lies', 'Anna', 'Bauiley', NULL, NULL),
  ('Absolute Power', 'David', 'Balducci', NULL, NULL),
  ('Divine Justice', 'David', 'Balducci', 'Camel Club', '4'),
  ('Saving Faith', 'David', 'Balducci', NULL, NULL),
  ('Stone Cold', 'David', 'Balducci', 'Camel Club', '3'),
  ('The Camel Club #1', 'David', 'Balducci', NULL, NULL),
  ('The Collectors', 'David', 'Balducci', 'Camel Club', '2'),
  ('The Simple Truth', 'David', 'Balducci', NULL, NULL),
  ('The Innocent', 'David', 'Balducci', 'Will Robie', '1'),
  ('The Forgotten', 'David', 'Balducci', 'John Puller', '2'),
  ('The Target', 'David', 'Balducci', 'Will Robie', '3'),
  ('The Escape', 'David', 'Balducci', 'John Puller', '3'),
  ('The Winner', 'David', 'Balducci', NULL, NULL),
  ('Total Control', 'David', 'Balducci', NULL, NULL),
  ('Memory Man', 'David', 'Balducci', 'Amos Decker', '1'),
  ('The Last Mile', 'David', 'Balducci', 'Amos Decker', '2'),
  ('The Guilty', 'David', 'Balducci', 'Will Robie', '4'),
  ('The Fix', 'David', 'Balducci', 'Amos Decker', '3'),
  ('Zero Day', 'David', 'Balducci', 'John Puller', '1'),
  ('End Game', 'David', 'Balducci', 'Will Robie', '5'),
  ('The Fallen', 'David', 'Balducci', 'Amos Decker', '4'),
  ('The Long Road to Mercy', 'David', 'Balducci', 'Atlee Pine', '1'),
  ('The Hit', 'David', 'Balducci', 'Will Robie', '2'),
  ('Redemption', 'David', 'Balducci', 'Amos Decker', '5'),
  ('One Good Deed', 'David', 'Balducci', 'Archer', '1'),
  ('Walk The Wire', 'David', 'Balducci', 'Amos Decker', '6'),
  ('A Minute to Midnight', 'David', 'Balducci', 'Atlee Pine', '2'),
  ('Daylight', 'David', 'Balducci', 'Atlee Pine', '3'),
  ('A Gambling Man', 'David', 'Balducci', 'Archer', '2'),
  ('Mercy', 'David', 'Balducci', 'Atlee Pine', '4'),
  ('Dream Town', 'David', 'Balducci', 'Archer', '3'),
  ('Long Shadows', 'David', 'Balducci', 'Amos Decker', '7'),
  ('The 6:20 Man', 'David', 'Balducci', NULL, NULL),
  ('Simply Lies', 'David', 'Balducci', NULL, NULL),
  ('Hour Game (King and Maxwell)', 'David', 'Balducci', NULL, NULL),
  ('To Die For (6:20 Man)', 'David', 'Balducci', NULL, NULL),
  ('A Calamity of Souls', 'David', 'Balducci', NULL, NULL),
  ('The Edge (6:20 Man)', 'David', 'Balducci', NULL, NULL),
  ('Strangers in Time', 'David', 'Balducci', NULL, NULL),
  ('Nash Falls (Part 1)', 'David', 'Balducci', NULL, NULL),
  ('Nash Rises (Part 2)', 'David', 'Balducci', NULL, NULL),
  ('Snow', 'John', 'Banville', NULL, NULL),
  ('April in Spain', 'John', 'Banville', NULL, NULL),
  ('Blacklands', 'Belinda', 'Bauer', NULL, NULL),
  ('The Vanishing Half', 'Brit', 'Bennett', NULL, NULL),
  ('Cruel Justice', 'William', 'Bernhardt', NULL, NULL),
  ('The Templar Legacy', 'Steve', 'Berry', NULL, NULL),
  ('The Patriot Threat', 'Steve', 'Berry', NULL, NULL),
  ('Afterland', 'Lauren', 'Beukes', NULL, NULL),
  ('The Shining Girls', 'Lauren', 'Beukes', NULL, NULL),
  ('Double Blind', 'Chris', 'Bohjalian', NULL, NULL),
  ('Open Season', 'C.J.', 'Box', 'Joe Pickett', '1'),
  ('Savage Run', 'C.J.', 'Box', 'Joe Pickett', '2'),
  ('Winterkill', 'C.J.', 'Box', 'Joe Pickett', '3'),
  ('Trophy Hunt', 'C.J.', 'Box', 'Joe Pickett', '4'),
  ('Out of Range', 'C.J.', 'Box', 'Joe Pickett', '5'),
  ('In Plain Sight', 'C.J.', 'Box', 'Joe Pickett', '6'),
  ('Free Fire', 'C.J.', 'Box', 'Joe Pickett', '10'),
  ('Blood Trail', 'C.J.', 'Box', 'Joe Pickett', '7'),
  ('Below Zero', 'C.J.', 'Box', 'Joe Pickett', '8'),
  ('Nowhere to Run', 'C.J.', 'Box', 'Joe Pickett', '9'),
  ('Cold Wind', 'C.J.', 'Box', 'Joe Pickett', '11'),
  ('Force of Nature', 'C.J.', 'Box', 'Joe Pickett', '12'),
  ('Breaking Point', 'C.J.', 'Box', 'Joe Pickett', '13'),
  ('Stone Cold', 'C.J.', 'Box', 'Joe Pickett', '14'),
  ('Endangered', 'C.J.', 'Box', 'Joe Pickett', '15'),
  ('Blue Heaven', 'C.J.', 'Box', NULL, NULL),
  ('Off the Grid', 'C.J.', 'Box', 'Joe Pickett', '16'),
  ('Vicious Circle', 'C.J.', 'Box', 'Joe Pickett', '17'),
  ('The Disappeared', 'C.J.', 'Box', 'Joe Pickett', '18'),
  ('The Highway', 'C.J.', 'Box', 'Cassie Dewell', '1'),
  ('Paradise Valley', 'C.J.', 'Box', 'Cassie Dewell', '4'),
  ('Wolf Pack', 'C.J.', 'Box', 'Joe Pickett', '19'),
  ('Long Range', 'C.J.', 'Box', 'Joe Pickett', '20'),
  ('The Bi erroots', 'C.J.', 'Box', 'Cassie Dewell', '3'),
  ('Dark Sky', 'C.J.', 'Box', 'Joe Pickett', '21'),
  ('Shadows Reel', 'C.J.', 'Box', 'Joe Pickett', '22'),
  ('Treasure State', 'C.J.', 'Box', 'Cassie Dewell', '5'),
  ('Storm Watch', 'C.J.', 'Box', 'Joe Pickett', '23'),
  ('Three Inch Teeth', 'C.J.', 'Box', 'Joe Pickett', '24'),
  ('Ba le Mountain', 'C.J.', 'Box', 'Joe Pickett', '25'),
  ('The Crossroads', 'C.J.', 'Box', 'Joe Pickett', '26'),
  ('Fahrenheit 451', 'Ray', 'Bradbury', NULL, NULL),
  ('The Mar an Chronicles', 'Ray', 'Bradbury', NULL, NULL),
  ('American Moonshot', 'Douglas', 'Brinkley', NULL, NULL),
  ('The Greatest Genera on', 'Tom', 'Brokaw', NULL, NULL),
  ('A Lucky Life Interrupted', 'Tom', 'Brokaw', NULL, NULL),
  ('Angels and Demons', 'Dan', 'Brown', NULL, NULL),
  ('Decep on Point', 'Dan', 'Brown', NULL, NULL),
  ('Digital Fortress', 'Dan', 'Brown', NULL, NULL),
  ('The DaVinci Code', 'Dan', 'Brown', NULL, NULL),
  ('The Lost Symbol', 'Dan', 'Brown', NULL, NULL),
  ('Inferno', 'Dan', 'Brown', NULL, NULL),
  ('Origin', 'Dan', 'Brown', NULL, NULL),
  ('The Secret of Secrets', 'Dan', 'Brown', NULL, NULL),
  ('The Boys in the Boat', 'Daniel James', 'Brown', NULL, NULL),
  ('Facing the Mountain', 'Daniel James', 'Brown', NULL, NULL),
  ('Bury My Heart at Wounded Knee', 'Dee', 'Brown', NULL, NULL),
  ('Red Rising', 'Pierce', 'Brown', NULL, NULL),
  ('Golden Son', 'Pierce', 'Brown', NULL, NULL),
  ('Morning Star', 'Pierce', 'Brown', NULL, NULL),
  ('Thick as Thieves', 'Sandra', 'Brown', NULL, NULL),
  ('Overkill', 'Sandra', 'Brown', NULL, NULL),
  ('A ermath', 'Levar', 'Burton', NULL, NULL),
  ('Kindred', 'Octavia', 'Butler', NULL, NULL),
  ('Parable of the Sower', 'Octavia', 'Butler', NULL, NULL),
  ('Parable of the Talents', 'Octavia', 'Butler', NULL, NULL),
  ('All The Water In The World', 'Eiren', 'Ca all', NULL, NULL),
  ('The Rule of Four', 'Ian', 'Caldwell', NULL, NULL),
  ('Open Carry', 'Marc', 'Cameron', 'Arliss Cu er', '1'),
  ('Stone Cross', 'Marc', 'Cameron', 'Arliss Cu er', '2'),
  ('Bone Ra le', 'Marc', 'Cameron', 'Arliss Cu er', '3'),
  ('Cold Snap', 'Marc', 'Cameron', 'Arliss Cu er', '4'),
  ('Breakneck', 'Marc', 'Cameron', 'Arliss Cu er', '5'),
  ('In Cold Blood', 'Truman', 'Capote', NULL, NULL),
  ('Blaze Me a Sun', 'Christopher', 'Carlsson', NULL, NULL),
  ('Under The Storm', 'Christopher', 'Carlsson', NULL, NULL),
  ('The Alienist', 'Caleb', 'Carr', NULL, NULL),
  ('The Angel of Darkness', 'Caleb', 'Carr', NULL, NULL),
  ('Surrender, New York', 'Caleb', 'Carr', NULL, NULL),
  ('61 Hours', 'Lee', 'Child', NULL, NULL),
  ('Bad Luck and Trouble', 'Lee', 'Child', NULL, NULL),
  ('Gone Tomorrow', 'Lee', 'Child', NULL, NULL),
  ('One Shot', 'Lee', 'Child', NULL, NULL),
  ('Persuader', 'Lee', 'Child', NULL, NULL),
  ('Running Blind', 'Lee', 'Child', NULL, NULL),
  ('The Enemy', 'Lee', 'Child', NULL, NULL),
  ('The Hard Way', 'Lee', 'Child', NULL, NULL),
  ('Tripwire', 'Lee', 'Child', NULL, NULL),
  ('Worth Dying For', 'Lee', 'Child', NULL, NULL),
  ('Nothing to Lose', 'Lee', 'Child', NULL, NULL),
  ('Killing Floor', 'Lee', 'Child', NULL, NULL),
  ('Die Trying', 'Lee', 'Child', NULL, NULL),
  ('Without Fail', 'Lee', 'Child', NULL, NULL),
  ('Echo Burning', 'Lee', 'Child', NULL, NULL),
  ('Second Son', 'Lee', 'Child', NULL, NULL),
  ('Deep Down', 'Lee', 'Child', NULL, NULL),
  ('The Affair', 'Lee', 'Child', NULL, NULL),
  ('Personal', 'Lee', 'Child', NULL, NULL),
  ('A Wanted Man', 'Lee', 'Child', NULL, NULL),
  ('Never Go Back', 'Lee', 'Child', NULL, NULL),
  ('Make Me', 'Lee', 'Child', NULL, NULL),
  ('Night School', 'Lee', 'Child', NULL, NULL),
  ('The Midnight Line', 'Lee', 'Child', NULL, NULL),
  ('The Christmas Scorpion (Short Story)', 'Lee', 'Child', NULL, NULL),
  ('Past Tense', 'Lee', 'Child', NULL, NULL),
  ('Blue Moon', 'Lee', 'Child', NULL, NULL),
  ('The Sen nel (with Andrew Child)', 'Lee', 'Child', NULL, NULL),
  ('Be er o Dead (with Andrew Child)', 'Lee', 'Child', NULL, NULL),
  ('No Plan B (with Andrew Child)', 'Lee', 'Child', NULL, NULL),
  ('Exit Strategy (with Andrew Child)', 'Lee', 'Child', NULL, NULL),
  ('In Too Deep (with Andrew Child)', 'Lee', 'Child', NULL, NULL),
  ('Flux', 'Jinwoo', 'Chong', NULL, NULL),
  ('A Thousand Yesteryears', 'Mae', 'Claire', NULL, NULL),
  ('Dead or Alive', 'Tom', 'Clancy', NULL, NULL),
  ('Debt of Honor', 'Tom', 'Clancy', NULL, NULL),
  ('Execu ve Orders', 'Tom', 'Clancy', NULL, NULL),
  ('Locked On', 'Tom', 'Clancy', NULL, NULL),
  ('Patriot Games', 'Tom', 'Clancy', NULL, NULL),
  ('Rainbow Six', 'Tom', 'Clancy', NULL, NULL),
  ('Red Rabbit', 'Tom', 'Clancy', NULL, NULL),
  ('Red Storm Rising', 'Tom', 'Clancy', NULL, NULL),
  ('The Bear and the Dragon', 'Tom', 'Clancy', NULL, NULL),
  ('The Cardinal of the Kremlin', 'Tom', 'Clancy', NULL, NULL),
  ('The Hunt for Red October', 'Tom', 'Clancy', NULL, NULL),
  ('The Sum of All Fears', 'Tom', 'Clancy', NULL, NULL),
  ('The Teeth of the Tiger', 'Tom', 'Clancy', NULL, NULL),
  ('Without Remores', 'Tom', 'Clancy', NULL, NULL),
  ('Locked On (Mark Greaney)', 'Tom', 'Clancy', NULL, NULL),
  ('Threat Vector (Mark Greaney)', 'Tom', 'Clancy', NULL, NULL),
  ('Command Authority (Mark Greaney)', 'Tom', 'Clancy', NULL, NULL),
  ('Under Fire (Grant Blackwood)', 'Tom', 'Clancy', NULL, NULL),
  ('Comander in Chief (Mark Greaney)', 'Tom', 'Clancy', NULL, NULL),
  ('Full Force and E ect (Mark Greaney)', 'Tom', 'Clancy', NULL, NULL),
  ('True Faith and Allegiance (Mark Greaney)', 'Tom', 'Clancy', NULL, NULL),
  ('Power Empire (Marc Cameron)', 'Tom', 'Clancy', NULL, NULL),
  ('Line of Sight (Mike Maden)', 'Tom', 'Clancy', NULL, NULL),
  ('Oath of O ce (Marc Cameron)', 'Tom', 'Clancy', NULL, NULL),
  ('Enemy Contact (Mark Maden)', 'Tom', 'Clancy', NULL, NULL),
  ('Code of Honor (Marc Cameron)', 'Tom', 'Clancy', NULL, NULL),
  ('Shadow of the Dragon (Marc Cameron)', 'Tom', 'Clancy', NULL, NULL),
  ('Firing Point (Mike Maden)', 'Tom', 'Clancy', NULL, NULL),
  ('Zero Hour (Don Bentley)', 'Tom', 'Clancy', NULL, NULL),
  ('Red Winter (Marc Cameron)', 'Tom', 'Clancy', NULL, NULL),
  ('Chain of Command (Marc Cameron)', 'Tom', 'Clancy', NULL, NULL),
  ('Noble House', 'James', 'Clavell', NULL, NULL),
  ('Shogun', 'James', 'Clavell', NULL, NULL),
  ('TaiPan', 'James', 'Clavell', NULL, NULL),
  ('King Rat', 'James', 'Clavell', NULL, NULL),
  ('Deal Breaker', 'Harlan', 'Coben', NULL, NULL),
  ('Drop Shot', 'Harlan', 'Coben', NULL, NULL),
  ('Long Lost', 'Harlan', 'Coben', NULL, NULL),
  ('Play Dead', 'Harlan', 'Coben', NULL, NULL),
  ('Tell No One', 'Harlan', 'Coben', NULL, NULL),
  ('One False Move', 'Harlan', 'Coben', NULL, NULL),
  ('Fade Away', 'Harlan', 'Coben', NULL, NULL),
  ('Promise Me', 'Harlan', 'Coben', NULL, NULL),
  ('The Innocent', 'Harlan', 'Coben', NULL, NULL),
  ('Just One Look', 'Harlan', 'Coben', NULL, NULL),
  ('Caught', 'Harlan', 'Coben', NULL, NULL),
  ('Gone for Good', 'Harlan', 'Coben', NULL, NULL),
  ('No Second Chance', 'Harlan', 'Coben', NULL, NULL),
  ('Miracle Cure', 'Harlan', 'Coben', NULL, NULL),
  ('Stay Close', 'Harlan', 'Coben', NULL, NULL),
  ('Hold Tight', 'Harlan', 'Coben', NULL, NULL),
  ('Six Years', 'Harlan', 'Coben', NULL, NULL),
  ('Missing You', 'Harlan', 'Coben', NULL, NULL),
  ('The Woods', 'Harlan', 'Coben', NULL, NULL),
  ('The Stranger', 'Harlan', 'Coben', NULL, NULL),
  ('Darkest Fear', 'Harlan', 'Coben', NULL, NULL),
  ('Fool Me Once', 'Harlan', 'Coben', NULL, NULL),
  ('Home', 'Harlan', 'Coben', NULL, NULL),
  ('Don''t Let Go', 'Harlan', 'Coben', NULL, NULL),
  ('Run Away', 'Harlan', 'Coben', NULL, NULL),
  ('The Boy From the Woods', 'Harlan', 'Coben', NULL, NULL),
  ('Win', 'Harlan', 'Coben', NULL, NULL),
  ('The Match', 'Harlan', 'Coben', NULL, NULL),
  ('I Will Find You', 'Harlan', 'Coben', NULL, NULL),
  ('Think Twice', 'Harlan', 'Coben', NULL, NULL),
  ('The Hunger Games', 'Suzanne', 'Collins', NULL, NULL),
  ('Catching Fire', 'Suzanne', 'Collins', NULL, NULL),
  ('Mockingjay', 'Suzanne', 'Collins', NULL, NULL),
  ('Sunrise on the Reaping', 'Suzanne', 'Collins', NULL, NULL),
  ('Angels Flight', 'Michael', 'Connelly', NULL, NULL),
  ('Blood Work', 'Michael', 'Connelly', NULL, NULL),
  ('City of Bones', 'Michael', 'Connelly', NULL, NULL),
  ('Echo Park', 'Michael', 'Connelly', NULL, NULL),
  ('Lost Light', 'Michael', 'Connelly', NULL, NULL),
  ('The Black Echo', 'Michael', 'Connelly', NULL, NULL),
  ('The Black Ice', 'Michael', 'Connelly', NULL, NULL),
  ('The Brass Verdict', 'Michael', 'Connelly', NULL, NULL),
  ('The Last Coyote', 'Michael', 'Connelly', NULL, NULL),
  ('The Lincoln Lawyer', 'Michael', 'Connelly', NULL, NULL),
  ('The Narrows', 'Michael', 'Connelly', NULL, NULL),
  ('The Overlook', 'Michael', 'Connelly', NULL, NULL),
  ('The Poet', 'Michael', 'Connelly', NULL, NULL),
  ('The Scarecrow', 'Michael', 'Connelly', NULL, NULL),
  ('Trunk Music', 'Michael', 'Connelly', NULL, NULL),
  ('The Reversal', 'Michael', 'Connelly', NULL, NULL),
  ('The Drop (Harry Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('The Fi h Witness', 'Michael', 'Connelly', NULL, NULL),
  ('The Black Box (Harry Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('The Gods of Guilt', 'Michael', 'Connelly', NULL, NULL),
  ('The Burning Room (Harry Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('The Crossing (Harry Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('The Wrong Side of of Goodbye (Harry Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('A Darkness More Than Night (Harry Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('The Late Show', 'Michael', 'Connelly', 'Renee Ballard', '1'),
  ('Two Kinds of Truth', 'Michael', 'Connelly', 'Harry Bosch', '20'),
  ('Dark Sacred Night', 'Michael', 'Connelly', 'Harry Bosch #21; Renee Ballard', '2'),
  ('The Night Fire', 'Michael', 'Connelly', 'Harry Bosch #22; Renee Ballard', '3'),
  ('The Dark Hours', 'Michael', 'Connelly', 'Harry Bosch #23; Renee Ballard', '4'),
  ('Fair Warning', 'Michael', 'Connelly', NULL, NULL),
  ('The Law of Innocence (Mickey Haller)', 'Michael', 'Connelly', NULL, NULL),
  ('Resurrec on Walk (Mickey Haller & Harry Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('Desert Star', 'Michael', 'Connelly', 'Harry Bosch #24; Renee Ballard', '5'),
  ('The Wai ng (Ballard & Bosch)', 'Michael', 'Connelly', NULL, NULL),
  ('Nightshade (S lwell)', 'Michael', 'Connelly', NULL, NULL),
  ('The Proving Ground (Mickey Haller)', 'Michael', 'Connelly', NULL, NULL),
  ('Blow Fly', 'Patricia', 'Cornwell', NULL, NULL),
  ('Body of Evidence', 'Patricia', 'Cornwell', NULL, NULL),
  ('Book of the Dead', 'Patricia', 'Cornwell', NULL, NULL),
  ('Cause of Death', 'Patricia', 'Cornwell', NULL, NULL),
  ('Cruel and Unusual', 'Patricia', 'Cornwell', NULL, NULL),
  ('From Po er''s Field', 'Patricia', 'Cornwell', NULL, NULL),
  ('Point of Origin', 'Patricia', 'Cornwell', NULL, NULL),
  ('Post Mortem', 'Patricia', 'Cornwell', NULL, NULL),
  ('Predator', 'Patricia', 'Cornwell', NULL, NULL),
  ('The Last Precinct', 'Patricia', 'Cornwell', NULL, NULL),
  ('The Scarpe a Factor', 'Patricia', 'Cornwell', NULL, NULL),
  ('Iden ty Unknown', 'Patricia', 'Cornwell', NULL, NULL),
  ('Leviathan Wakes', 'James S. A.', 'Corey', NULL, NULL),
  ('The Power of One', 'Bryce', 'Courtenoy', NULL, NULL),
  ('Suspect', 'Robert', 'Crais', NULL, NULL),
  ('The Monkey''s Raincoat (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Stalking the Angel (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Lullaby Town (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Free Fall (Elvis Cole and Joe Pike)', 'Robert', 'Crais', NULL, NULL),
  ('Vodoo River (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Demoli on Angel', 'Robert', 'Crais', NULL, NULL),
  ('LA Requiem (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('The Last Detec ve (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Indigo Slam (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Sunset Express (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Chasing Darkness (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('The Forgotten Man (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('The Two Minute Rule', 'Robert', 'Crais', NULL, NULL),
  ('Taken (Elvis Cole and Joe Pike)', 'Robert', 'Crais', NULL, NULL),
  ('The First Rule (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('The Sentry (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('The Promise (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('The Watchman (Elvis Cole)', 'Robert', 'Crais', NULL, NULL),
  ('Wanted (Elvis Cole and Joe Pike)', 'Robert', 'Crais', NULL, NULL),
  ('A Dangerous Man (Elvis Cole and Joe Pike)', 'Robert', 'Crais', NULL, NULL),
  ('Racing the Light (Elvis Cole and Joe Pike)', 'Robert', 'Crais', NULL, NULL),
  ('The Big Empty (Elvis Cole and Joe Pike)', 'Robert', 'Crais', NULL, NULL),
  ('Airframe', 'Michael', 'Crichton', NULL, NULL),
  ('Congo', 'Michael', 'Crichton', NULL, NULL),
  ('Disclosure', 'Michael', 'Crichton', NULL, NULL),
  ('Jurassic Park', 'Michael', 'Crichton', NULL, NULL),
  ('Next', 'Michael', 'Crichton', NULL, NULL),
  ('Pirate La tudes', 'Michael', 'Crichton', NULL, NULL),
  ('Prey', 'Michael', 'Crichton', NULL, NULL),
  ('Rising Sun', 'Michael', 'Crichton', NULL, NULL),
  ('Sphere', 'Michael', 'Crichton', NULL, NULL),
  ('State of Fear', 'Michael', 'Crichton', NULL, NULL),
  ('The Andromeda Strain', 'Michael', 'Crichton', NULL, NULL),
  ('The Lost World', 'Michael', 'Crichton', NULL, NULL),
  ('Timeline', 'Michael', 'Crichton', NULL, NULL),
  ('Charlie Wilson''s War', 'George', 'Crile', NULL, NULL),
  ('The Passage', 'Jus n', 'Cronin', 'Passage Trilogy', '1'),
  ('The Twelve', 'Jus n', 'Cronin', 'Passage Trilogy', '2'),
  ('The City of Mirrors', 'Jus n', 'Cronin', 'Passage Trilogy', '3'),
  ('Dark Ma er', 'Blake', 'Crouch', NULL, NULL),
  ('American Dirt', 'Jeanine', 'Cummins', NULL, NULL),
  ('Plague Ship (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('Corsair (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('Atlan s Found (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Black Wind (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Dark Watch (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('Deep Six (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Inca Gold (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Lost City (Kurt Aus n)', 'Clive', 'Cussler', NULL, NULL),
  ('Sahara (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Skeleton Coast (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('The Chase (Isaac Bell)', 'Clive', 'Cussler', NULL, NULL),
  ('The Mediterranean Caper (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Treasure of Khan (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Trojan Odyssey (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('The Navigator(Kurt Aus n)', 'Clive', 'Cussler', NULL, NULL),
  ('Poseidon''s Arrow (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('The Jungle (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('Havana Storm (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Piranha (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('The Emperor''s Revenge (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('Mirage (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('Odessa Sea (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('Typhoon Fury (Oregon Files)', 'Clive', 'Cussler', NULL, NULL),
  ('The Silent Sea', 'Clive', 'Cussler', 'Oregon Files', '7'),
  ('Flood Tide', 'Clive', 'Cussler', NULL, NULL),
  ('Golden Budha', 'Clive', 'Cussler', 'Oregon Files', '1'),
  ('Shadow Tyrants', 'Clive', 'Cussler', 'Oregon Files', '13'),
  ('Final Op on', 'Clive', 'Cussler', 'Oregon Files', '14'),
  ('Cel c Empire (Dirk Pi )', 'Clive', 'Cussler', NULL, NULL),
  ('The Titanic Secret (Isaac Bell)', 'Clive', 'Cussler', NULL, NULL),
  ('Marauder', 'Clive', 'Cussler', 'Oregon Files', '15'),
  ('The Bone Collector (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Burning Wire (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Co n Dancer (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Cold Moon (Lincoln Rhyme/Kathryn Dance)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Empty Chair (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Sleeping Doll (Kathryn Dance)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Stone Monkey (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Twel h Card (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Vanished Man (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Broken Window (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Bodies Le Behind', 'Jeffrey', 'Deaver', NULL, NULL),
  ('Edge', 'Jeffrey', 'Deaver', NULL, NULL),
  ('XO (Lincoln Rhyme/Kathryn Dance)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('Garden of Beasts', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Kill Room (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The October List', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Blue Nowhere', 'Jeffrey', 'Deaver', NULL, NULL),
  ('Solitude Creek (Kathryn Dance)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('Roadside Crosses (Kathryn Dance)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Steel Kiss (Lincoln Rhyme)', 'Jeffrey', 'Deaver', NULL, NULL),
  ('The Burial Hour', 'Jeffrey', 'Deaver', 'Lincoln Rhyme', '13'),
  ('The Never Game', 'Jeffrey', 'Deaver', 'Colter Shaw', '1'),
  ('The Goodbye Man', 'Jeffrey', 'Deaver', 'Colter Shaw', '2'),
  ('The Final Twist', 'Jeffrey', 'Deaver', 'Colter Shaw', '3'),
  ('Hun ng Time', 'Jeffrey', 'Deaver', 'Colter Shaw', '4'),
  ('South of Nowhere', 'Jeffrey', 'Deaver', 'Colter Shaw', '5'),
  ('Night Fall', 'Nelson', 'DeMille', NULL, NULL),
  ('Spencerville', 'Nelson', 'DeMille', NULL, NULL),
  ('The Charm School', 'Nelson', 'DeMille', NULL, NULL),
  ('Cathedral', 'Nelson', 'DeMille', NULL, NULL),
  ('The Gate House', 'Nelson', 'DeMille', NULL, NULL),
  ('The General''s Daughter', 'Nelson', 'DeMille', NULL, NULL),
  ('The Gold Coast', 'Nelson', 'DeMille', NULL, NULL),
  ('The Lion''s Game', 'Nelson', 'DeMille', NULL, NULL),
  ('The Lion', 'Nelson', 'DeMille', NULL, NULL),
  ('Plum Island', 'Nelson', 'DeMille', NULL, NULL),
  ('Up Country', 'Nelson', 'DeMille', NULL, NULL),
  ('Word of Honor', 'Nelson', 'DeMille', NULL, NULL),
  ('The Panther', 'Nelson', 'DeMille', NULL, NULL),
  ('The Quest', 'Nelson', 'DeMille', NULL, NULL),
  ('The Quest (Updated version)', 'Nelson', 'DeMille', NULL, NULL),
  ('Radiant Angel', 'Nelson', 'DeMille', NULL, NULL),
  ('Wild Fire', 'Nelson', 'DeMille', NULL, NULL),
  ('The Cuban Affair', 'Nelson', 'DeMille', NULL, NULL),
  ('Rogue Island', 'Bruce', 'DeSilva', NULL, NULL),
  ('The Man in the High Castle', 'Philip K', 'Dick', NULL, NULL),
  ('The Enigma of Room 622', 'Joel', 'Dicker', NULL, NULL),
  ('Dungeon Crawler', 'Ma', 'Dinniman', NULL, NULL),
  ('All The Light We Cannot See', 'Anthony', 'Doerr', NULL, NULL),
  ('Crime and Punishment', 'Fyodor', 'Dostoyevsky', NULL, NULL),
  ('The Idiot', 'Fyodor', 'Dostoyevsky', NULL, NULL),
  ('Complete Sherlock Holmes', 'A. Conan', 'Doyle', NULL, NULL),
  ('The Count of Monte Cristo', 'Alexandre', 'Dumas', NULL, NULL),
  ('Joys of Motherhood', 'Buchi', 'Emecheta', NULL, NULL),
  ('Shuffler', 'Ramona', 'Emerson', NULL, NULL),
  ('Exposure', 'Ramona', 'Emerson', NULL, NULL),
  ('James', 'Percival', 'Evere', NULL, NULL),
  ('The Woman in the Window', 'AJ', 'Finn', NULL, NULL),
  ('Time A er Time', 'Jack', 'Finney', NULL, NULL),
  ('Time and Again', 'Jack', 'Finney', NULL, NULL),
  ('Woodrow Wilson''s Dime', 'Jack', 'Finney', NULL, NULL),
  ('Marion''s Wall', 'Jack', 'Finney', NULL, NULL),
  ('Extreme Measures (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('Pursuit of Honor (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('Term Limits (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('American Assassin (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('The Last Man (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('Kill Shot (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('Transfer of Power (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('The Third Op on (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('The Survivor (Mitch Rapp by Kyle Mills)', 'Vince', 'Flynn', NULL, NULL),
  ('Order to Kill (Mitch Rapp by Kyle Mills)', 'Vince', 'Flynn', NULL, NULL),
  ('Execu ve Power (Mitch Rapp)', 'Vince', 'Flynn', NULL, NULL),
  ('Red War (Mitch Rapp by Kyle Mills)', 'Vince', 'Flynn', NULL, NULL),
  ('Lethal Agent (Mitch Rapp by Kyle Mills)', 'Vince', 'Flynn', NULL, NULL),
  ('Total Power (Mitch Rapp by Kyle Mills)', 'Vince', 'Flynn', NULL, NULL),
  ('Code Red (Mitch Rapp by Kyle Mills)', 'Vince', 'Flynn', NULL, NULL),
  ('Oath of Loyalty (Mitch Rapp by Kyle Mills)', 'Vince', 'Flynn', NULL, NULL),
  ('Capture or Kill (Mitch Rapp by Don Bentley)', 'Vince', 'Flynn', NULL, NULL),
  ('Eye of the Needle', 'Ken', 'Folle', NULL, NULL),
  ('Lie Down with Lions', 'Ken', 'Folle', NULL, NULL),
  ('Night Over Water', 'Ken', 'Folle', NULL, NULL),
  ('On Wings of Eagles', 'Ken', 'Folle', NULL, NULL),
  ('The Hammer of Eden', 'Ken', 'Folle', NULL, NULL),
  ('The Key to Rebecca', 'Ken', 'Folle', NULL, NULL),
  ('The Man from St. Petersburg', 'Ken', 'Folle', NULL, NULL),
  ('The Pillars of the Earth', 'Ken', 'Folle', NULL, NULL),
  ('The Third Twin', 'Ken', 'Folle', NULL, NULL),
  ('Triple', 'Ken', 'Folle', NULL, NULL),
  ('Fall of Giants', 'Ken', 'Folle', 'The Century Trilogy', '1'),
  ('Winter of the World', 'Ken', 'Folle', 'The Century Trilogy', '2'),
  ('Edge of Eternity', 'Ken', 'Folle', 'The Century Trilogy', '3'),
  ('The Day of the Jackel', 'Frederick', 'Forsyth', NULL, NULL),
  ('The Odessa File', 'Frederick', 'Forsyth', NULL, NULL),
  ('The Kill List', 'Frederick', 'Forsyth', NULL, NULL),
  ('In the Woods', 'Tana', 'French', NULL, NULL),
  ('The Likeness', 'Tana', 'French', NULL, NULL),
  ('Faithful Place', 'Tana', 'French', NULL, NULL),
  ('Broken Harbor', 'Tana', 'French', NULL, NULL),
  ('The Searcher', 'Tana', 'French', NULL, NULL),
  ('The Secret Place', 'Tana', 'French', NULL, NULL),
  ('The Trespasser', 'Tana', 'French', NULL, NULL),
  ('The Witch Elm', 'Tana', 'French', NULL, NULL),
  ('The Hunter', 'Tana', 'French', NULL, NULL),
  ('The Keeper', 'Tana', 'French', NULL, NULL),
  ('From Beirut to Jerusalem', 'Thomas', 'Friedman', NULL, NULL),
  ('Longitudes and A tudes', 'Thomas', 'Friedman', NULL, NULL),
  ('The World is Flat', 'Thomas', 'Friedman', NULL, NULL),
  ('The Cuckoo''s Calling', 'Robert', 'Galbraith', 'Cormoran Strike', '1'),
  ('The Silkworm', 'Robert', 'Galbraith', 'Cormoran Strike', '2'),
  ('Career of Evil', 'Robert', 'Galbraith', 'Cormoran Strike', '3'),
  ('Lethal White', 'Robert', 'Galbraith', 'Cormoran Strike', '4'),
  ('Troubled Blood', 'Robert', 'Galbraith', 'Cormoran Strike', '5'),
  ('The Running Grave', 'Robert', 'Galbraith', 'Cormoran Strike', '7'),
  ('The Hallmarked Man', 'Robert', 'Galbraith', 'Cormoran Strike', '8'),
  ('Lessons in Chemistry', 'Bonnie', 'Garmus', NULL, NULL),
  ('Le Unsaid', 'Jared', 'Glenn', NULL, NULL),
  ('Lost in the Sun', 'Jared', 'Glenn', NULL, NULL),
  ('The Lord of the Flies', 'William', 'Golding', NULL, NULL),
  ('The Law of Nines', 'Terry', 'Goodkind', NULL, NULL),
  ('Team of Rivals', 'Doris Kearns', 'Goodwin', NULL, NULL),
  ('A Reliable Wife', 'Robert', 'Goolrick', NULL, NULL),
  ('The Tin Drum', 'Günter', 'Grass', NULL, NULL),
  ('The Gray Man', 'Mark', 'Greany', NULL, NULL),
  ('On Target', 'Mark', 'Greany', 'Gray Man', '2'),
  ('Ballis c', 'Mark', 'Greany', 'Gray Man', '3'),
  ('Dead Eye', 'Mark', 'Greany', 'Gray Man', '4'),
  ('Back Blast', 'Mark', 'Greany', 'Gray Man', '5'),
  ('Gunmetal Gray', 'Mark', 'Greany', 'Gray Man', '6'),
  ('Agent in Place', 'Mark', 'Greany', 'Gray Man', '7'),
  ('Mission Cri cal', 'Mark', 'Greany', 'Gray Man', '8'),
  ('One Minute Out', 'Mark', 'Greany', 'Gray Man', '9'),
  ('Relentless', 'Mark', 'Greany', 'Gray Man', '10'),
  ('Sierra Six', 'Mark', 'Greany', 'Gray Man', '11'),
  ('Burner', 'Mark', 'Greany', 'Gray Man', '12'),
  ('Midnight Black', 'Mark', 'Greany', 'Gray Man', '13'),
  ('An Absolutely Remarkable Thing', 'Hank', 'Green', NULL, NULL),
  ('Exact Revenge', 'Tim', 'Green', NULL, NULL),
  ('When Gore Beat Bush-A Poli cal Fable', 'Jeffrey', 'Green eld', NULL, NULL),
  ('The Spook Who Sat By the Door', 'Sam', 'Greenlee', NULL, NULL),
  ('Black Ops', 'W.E.B.', 'Gri n', NULL, NULL),
  ('By Order of the President', 'W.E.B.', 'Gri n', NULL, NULL),
  ('The Hunters', 'W.E.B.', 'Gri n', NULL, NULL),
  ('The Shooters', 'W.E.B.', 'Gri n', NULL, NULL),
  ('The Outlaws', 'W.E.B.', 'Gri n', NULL, NULL),
  ('Covert Warriors', 'W.E.B.', 'Gri n', NULL, NULL),
  ('A Time to Kill', 'John', 'Grisham', NULL, NULL),
  ('The Brethren', 'John', 'Grisham', NULL, NULL),
  ('The Chamber', 'John', 'Grisham', NULL, NULL),
  ('The Client', 'John', 'Grisham', NULL, NULL),
  ('The Firm', 'John', 'Grisham', NULL, NULL),
  ('The Partner', 'John', 'Grisham', NULL, NULL),
  ('The Pelican Brief', 'John', 'Grisham', NULL, NULL),
  ('The Rainmaker', 'John', 'Grisham', NULL, NULL),
  ('The Street Lawyer', 'John', 'Grisham', NULL, NULL),
  ('The Racketeer', 'John', 'Grisham', NULL, NULL),
  ('Sycamore Road', 'John', 'Grisham', NULL, NULL),
  ('The Whistler', 'John', 'Grisham', NULL, NULL),
  ('The Rooster Bar', 'John', 'Grisham', NULL, NULL),
  ('The Guardians', 'John', 'Grisham', NULL, NULL),
  ('Camino Winds', 'John', 'Grisham', NULL, NULL),
  ('A Time for Mercy', 'John', 'Grisham', NULL, NULL),
  ('The Boys from Biloxi', 'John', 'Grisham', NULL, NULL),
  ('Camino Ghosts', 'John', 'Grisham', NULL, NULL),
  ('Forever', 'Pete', 'Hamill', NULL, NULL),
  ('North River', 'Pete', 'Hamill', NULL, NULL),
  ('Tabloid City', 'Pete', 'Hamill', NULL, NULL),
  ('Snow in August', 'Pete', 'Hamill', NULL, NULL),
  ('A Drinking Life', 'Pete', 'Hamill', NULL, NULL),
  ('The Great Alone', 'Kristen', 'Hannah', NULL, NULL),
  ('The Nigh ngale', 'Kristen', 'Hannah', NULL, NULL),
  ('The Four Winds', 'Kristen', 'Hannah', NULL, NULL),
  ('The Women', 'Kristen', 'Hannah', NULL, NULL),
  ('Conclave', 'Robert', 'Harris', NULL, NULL),
  ('The History of History', 'Ida', 'Ha emer-Higgins', NULL, NULL),
  ('The Girl on the Train', 'Paula', 'Hawkins', NULL, NULL),
  ('Before the Fall', 'Noah', 'Hawley', NULL, NULL),
  ('The Scarlet Le er', 'Nathaniel', 'Hawthorne', NULL, NULL),
  ('Hayes', 'Terry', 'Colleen', NULL, NULL),
  ('Hayes', 'Terry', 'Khaled', NULL, NULL),
  ('Heaberlin', 'Julia', 'Khaled', NULL, NULL),
  ('Heller', 'Joseph', 'Khaled', NULL, NULL),
  ('Hemingway', 'Ernest', 'Georgia', NULL, NULL),
  ('Hemingway', 'Ernest', 'Stephen', NULL, NULL),
  ('Herbert', 'Frank', 'Stephen', NULL, NULL),
  ('Herron', 'Mick', 'Stephen', NULL, NULL),
  ('Hilldenbrand', 'Laura', 'Stephen', NULL, NULL),
  ('Hirsch', 'James', 'Stephen', NULL, NULL),
  ('Holmes', 'Rupert', 'Stephen', NULL, NULL),
  ('Compulsion', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Decep on Point', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Devil''s Waltz', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Gone', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Private Eyes', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Rage', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Silent Partner', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Therapy', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Time Bomb', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Twisted', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Heartbreak Hotel', 'Jonathan', 'Kellerman', NULL, NULL),
  ('Burial Rites', 'Hannah', 'Kent', NULL, NULL),
  ('Carrie', 'Stephen', 'King', NULL, NULL),
  ('Cell', 'Stephen', 'King', NULL, NULL),
  ('Chris ne', 'Stephen', 'King', NULL, NULL),
  ('Firestarter', 'Stephen', 'King', NULL, NULL),
  ('Misery', 'Stephen', 'King', NULL, NULL),
  ('The Talisman (with Peter Straub)', 'Stephen', 'King', NULL, NULL),
  ('The Dead Zone', 'Stephen', 'King', NULL, NULL),
  ('The Green Mile', 'Stephen', 'King', NULL, NULL),
  ('The Running Man', 'Stephen', 'King', NULL, NULL),
  ('The Shining', 'Stephen', 'King', NULL, NULL),
  ('The Stand', 'Stephen', 'King', NULL, NULL),
  ('Thinner', 'Stephen', 'King', NULL, NULL),
  ('11/22/63', 'Stephen', 'King', NULL, NULL),
  ('Mr. Mercedes', 'Stephen', 'King', NULL, NULL),
  ('Finders Keepers', 'Stephen', 'King', NULL, NULL),
  ('End of Watch', 'Stephen', 'King', NULL, NULL),
  ('The Outsider', 'Stephen', 'King', NULL, NULL),
  ('The Long Walk', 'Stephen', 'King', NULL, NULL),
  ('On Wri ng', 'Stephen', 'King', NULL, NULL),
  ('Later (A true crime novel)', 'Stephen', 'King', NULL, NULL),
  ('Billy Summers', 'Stephen', 'King', NULL, NULL),
  ('Mr. Harrigan''s Phone', 'Stephen', 'King', NULL, NULL),
  ('The Life of Chuck', 'Stephen', 'King', NULL, NULL),
  ('If It Bleeds', 'Stephen', 'King', NULL, NULL),
  ('Rat', 'Stephen', 'King', NULL, NULL),
  ('Fairy Tale', 'Stephen', 'King', NULL, NULL),
  ('The Gunslinger (Dark Tower I)', 'Stephen', 'King', NULL, NULL),
  ('The Drawing of the Three (Dark Tower II)', 'Stephen', 'King', NULL, NULL),
  ('The Waste Lands (Dark Tower III)', 'Stephen', 'King', NULL, NULL),
  ('Wizard and Glass (Dark Tower IV)', 'Stephen', 'King', NULL, NULL),
  ('Wolves of the Calla (Dark Tower V)', 'Stephen', 'King', NULL, NULL),
  ('Song of Susannah (Dark Tower VI)', 'Stephen', 'King', NULL, NULL),
  ('The Dark Tower (Dark Tower VII)', 'Stephen', 'King', NULL, NULL),
  ('The Wind Through the Keyhole (Dark Tower extra)', 'Stephen', 'King', NULL, NULL),
  ('Holly', 'Stephen', 'King', NULL, NULL),
  ('Never Flinch', 'Stephen', 'King', NULL, NULL),
  ('Poisonwood Bible', 'Barbara', 'Kingsolver', NULL, NULL),
  ('Breathless', 'Dean', 'Koonz', NULL, NULL),
  ('Fear Nothing', 'Dean', 'Koonz', NULL, NULL),
  ('Intensity', 'Dean', 'Koonz', NULL, NULL),
  ('Lightning', 'Dean', 'Koonz', NULL, NULL),
  ('Sole Survivor', 'Dean', 'Koonz', NULL, NULL),
  ('The Husband', 'Dean', 'Koonz', NULL, NULL),
  ('Tick Tock', 'Dean', 'Koonz', NULL, NULL),
  ('Velocity', 'Dean', 'Koonz', NULL, NULL),
  ('Watchers', 'Dean', 'Koonz', NULL, NULL),
  ('Winter Moon', 'Dean', 'Koonz', NULL, NULL),
  ('Odd Thomas', 'Dean', 'Koonz', NULL, NULL),
  ('Forever Odd', 'Dean', 'Koonz', NULL, NULL),
  ('Brother Odd', 'Dean', 'Koonz', NULL, NULL),
  ('Odd Hours', 'Dean', 'Koonz', NULL, NULL),
  ('Deeply Odd', 'Dean', 'Koonz', NULL, NULL),
  ('Odd Apocalypse', 'Dean', 'Koonz', NULL, NULL),
  ('Saint Odd', 'Dean', 'Koonz', NULL, NULL),
  ('Innocence', 'Dean', 'Koonz', NULL, NULL),
  ('The City', 'Dean', 'Koonz', NULL, NULL),
  ('Ashley Bell', 'Dean', 'Koonz', NULL, NULL),
  ('The Big Dark Sky', 'Dean', 'Koonz', NULL, NULL),
  ('The Plot', 'Jean Han', 'Korelitz', NULL, NULL),
  ('The Sequel', 'Jean Han', 'Korelitz', NULL, NULL),
  ('Into Thin Air', 'Jon', 'Krakauer', NULL, NULL),
  ('The Girl in the Spider''s Web', 'David', 'Lagercrantz', 'Millenium Series', '4'),
  ('The Girl Who Takes an Eye for an Eye', 'David', 'Lagercrantz', 'Millenium Series', '5'),
  ('The Girl Who Lived Twice', 'David', 'Lagercrantz', 'Millenium Series', '6'),
  ('Defending Jacob', 'William', 'Landay', NULL, NULL),
  ('Mission Flats', 'William', 'Landay', NULL, NULL),
  ('The Strangler', 'William', 'Landay', NULL, NULL),
  ('The Couple Next Door', 'Shari', 'Lapena', NULL, NULL),
  ('The Devil in the White City', 'Erik', 'Larson', NULL, NULL),
  ('Thunderstruck', 'Erik', 'Larson', NULL, NULL),
  ('In the Garden of Beasts', 'Erik', 'Larson', NULL, NULL),
  ('Dead Wake', 'Erik', 'Larson', NULL, NULL),
  ('The Splendid and the Vile', 'Erik', 'Larson', NULL, NULL),
  ('The Girl Who Played with Fire', 'S eg', 'Larsson', 'Millenium Series', '1'),
  ('The Girl with the Dragon Tatoo', 'S eg', 'Larsson', 'Millenium Series', '2'),
  ('The Girl Who Kicked the Hornet''s Nest', 'S eg', 'Larsson', 'Millenium Series', '3'),
  ('Tinker Tailor Soldier Spy', 'John', 'Le Carré', NULL, NULL),
  ('A Most Wanted Man', 'John', 'Le Carré', NULL, NULL),
  ('A Perfect Spy', 'John', 'Le Carré', NULL, NULL),
  ('Our Game', 'John', 'Le Carré', NULL, NULL),
  ('Smiley''s People', 'John', 'Le Carré', NULL, NULL),
  ('The Constant Gardener', 'John', 'Le Carré', NULL, NULL),
  ('The Li le Drummer Girl', 'John', 'Le Carré', NULL, NULL),
  ('The Night Manager', 'John', 'Le Carré', NULL, NULL),
  ('The Russia House', 'John', 'Le Carré', NULL, NULL),
  ('The Spy Who Came in from the Cold', 'John', 'Le Carré', NULL, NULL),
  ('The Tailor of Panama', 'John', 'Le Carré', NULL, NULL),
  ('A Legacy of Spies', 'John', 'Le Carré', NULL, NULL),
  ('Agent Running in the Field', 'John', 'Le Carré', NULL, NULL),
  ('Silverview', 'John', 'Le Carré', NULL, NULL),
  ('To Kill A Mockingbird', 'Harper', 'Lee', NULL, NULL),
  ('The Breach', 'Patrick', 'Lee', NULL, NULL),
  ('Ghost Country', 'Patrick', 'Lee', NULL, NULL),
  ('Deep Sky', 'Patrick', 'Lee', NULL, NULL),
  ('The Runner', 'Patrick', 'Lee', NULL, NULL),
  ('Signal', 'Patrick', 'Lee', NULL, NULL),
  ('Shuffler Island', 'Dennis', 'Lehane', NULL, NULL),
  ('Gone Baby Gone', 'Dennis', 'Lehane', NULL, NULL),
  ('Moneyball', 'Michael', 'Lewis', NULL, NULL),
  ('Double Bind', 'Geo rey', 'Lo us', NULL, NULL),
  ('Lead Like Ike', 'Geo rey', 'Lo us', NULL, NULL),
  ('Saving Sarah', 'Geo rey', 'Lo us', NULL, NULL),
  ('The Dark Saint', 'Geo rey', 'Lo us', NULL, NULL),
  ('Dark Mirage', 'Geo rey', 'Lo us', 'Jack Tyrrell', '1'),
  ('Murderous Spirit', 'Geo rey', 'Lo us', 'Jack Tyrrell', '2'),
  ('The Last Thing', 'Geo rey', 'Lo us', 'Jack Tyrrell', '3'),
  ('Dangerous Purpose', 'Geo rey', 'Lo us', 'Jack Tyrrell', '4'),
  ('Fracture of the Soul', 'Geo rey', 'Lo us', 'Jack Tyrrell', '5'),
  ('No Traveler Returns', 'Geo rey', 'Lo us', 'Jack Tyrrell', '6'),
  ('Casual Slaughters', 'Geo rey', 'Lo us', 'Jack Tyrrell', '7'),
  ('Turn from Evil', 'Geo rey', 'Lo us', 'Jack Tyrrell', '8'),
  ('Purgatory', 'Geo rey', 'Lo us', 'Jack Tyrrell', '9'),
  ('The Devil''s Vaca on', 'Geo rey', 'Lo us', 'Jack Tyrrell', '10'),
  ('The Call of the Wild', 'Jack', 'London', NULL, NULL),
  ('Apollo 13', 'Jim', 'Lovell', NULL, NULL),
  ('The Apocalypse Watch', 'Robert', 'Ludlum', NULL, NULL),
  ('The Aquitaine Progression', 'Robert', 'Ludlum', NULL, NULL),
  ('The Bancro Strategy', 'Robert', 'Ludlum', NULL, NULL),
  ('The Bourne Decep on', 'Robert', 'Ludlum', NULL, NULL),
  ('The Bourne Iden ty', 'Robert', 'Ludlum', NULL, NULL),
  ('The Bourne Supremacy', 'Robert', 'Ludlum', NULL, NULL),
  ('The Bourne Ul matum', 'Robert', 'Ludlum', NULL, NULL),
  ('The Cassandra Compact', 'Robert', 'Ludlum', NULL, NULL),
  ('The Chancellor Manuscript', 'Robert', 'Ludlum', NULL, NULL),
  ('The Cry of the Halidon', 'Robert', 'Ludlum', NULL, NULL),
  ('The Gemini Contenders', 'Robert', 'Ludlum', NULL, NULL),
  ('The Holcro Covenant', 'Robert', 'Ludlum', NULL, NULL),
  ('The Icarus Agenda', 'Robert', 'Ludlum', NULL, NULL),
  ('The Matarese Circle', 'Robert', 'Ludlum', NULL, NULL),
  ('The Matarese Countdown', 'Robert', 'Ludlum', NULL, NULL),
  ('The Osterman Weekend', 'Robert', 'Ludlum', NULL, NULL),
  ('The Parsifal Mosaic', 'Robert', 'Ludlum', NULL, NULL),
  ('The Prometheus Decep on', 'Robert', 'Ludlum', NULL, NULL),
  ('The Rhineman Exchange', 'Robert', 'Ludlum', NULL, NULL),
  ('The Road to Gandolfo', 'Robert', 'Ludlum', NULL, NULL),
  ('The Road to Omaha', 'Robert', 'Ludlum', NULL, NULL),
  ('The Scarla Inheritance', 'Robert', 'Ludlum', NULL, NULL),
  ('The Scorpio Illusion', 'Robert', 'Ludlum', NULL, NULL),
  ('The Sigma Protocol', 'Robert', 'Ludlum', NULL, NULL),
  ('The Tristan Betrayal', 'Robert', 'Ludlum', NULL, NULL),
  ('Wicked', 'Gregory', 'Maguire', NULL, NULL),
  ('The Glory and the Dream', 'William', 'Manchester', NULL, NULL),
  ('Visions of Glory (Churchill Biography Volume 1)', 'William', 'Manchester', NULL, NULL),
  ('Alone (Churchill Biography Volume 2)', 'William', 'Manchester', NULL, NULL),
  ('Ma erhorn', 'Karl', 'Marlantes', NULL, NULL),
  ('Life of Pi', 'Yann', 'Martel', NULL, NULL),
  ('A Game of Thrones', 'George R.R.', 'Mar n', NULL, NULL),
  ('A Clash of Kings', 'George R.R.', 'Mar n', NULL, NULL),
  ('A Storm of Swords', 'George R.R.', 'Mar n', NULL, NULL),
  ('A Dance with Dragons', 'George R.R.', 'Mar n', NULL, NULL),
  ('A Feast with Crows', 'George R.R.', 'Mar n', NULL, NULL),
  ('Fire and Blood', 'George R.R.', 'Mar n', NULL, NULL),
  ('Wrong Place Wrong Time', 'Gillian', 'McAllister', NULL, NULL),
  ('The Heaven & Earth Grocery Store', 'James', 'McBride', NULL, NULL),
  ('Damascus Sta on', 'David', 'McCloskey', NULL, NULL),
  ('Moscow X', 'David', 'McCloskey', NULL, NULL),
  ('The Seventh Floor', 'David', 'McCloskey', NULL, NULL),
  ('The Persian', 'David', 'McCloskey', NULL, NULL),
  ('Truman', 'David', 'McCullough', NULL, NULL),
  ('Wright Brothers', 'David', 'McCullough', NULL, NULL),
  ('John Adams', 'David', 'McCullough', NULL, NULL),
  ('1776', 'David', 'McCullough', NULL, NULL),
  ('Saturday', 'Ian', 'McEwan', NULL, NULL),
  ('Amsterdam', 'Ian', 'McEwan', NULL, NULL),
  ('Atonement', 'Ian', 'McEwan', NULL, NULL),
  ('The North Water', 'Ian', 'McGuire', NULL, NULL),
  ('The Road', 'Cormac', 'McMcCarthy', NULL, NULL),
  ('The Inner Circle', 'Brad', 'Meltzer', NULL, NULL),
  ('The Fi h Assassin', 'Brad', 'Meltzer', NULL, NULL),
  ('The Escape Ar st', 'Brad', 'Meltzer', NULL, NULL),
  ('The Nazi Conspiracy (with Josh Mensch)', 'Brad', 'Meltzer', NULL, NULL),
  ('Moby-Dick', 'Herman', 'Melville', NULL, NULL),
  ('The Silent Pa ent', 'Alex', 'Michaelides', NULL, NULL),
  ('The Maidens', 'Alex', 'Michaelides', NULL, NULL),
  ('Caravans', 'James', 'Michener', NULL, NULL),
  ('Centennial', 'James', 'Michener', NULL, NULL),
  ('Iberia', 'James', 'Michener', NULL, NULL),
  ('Space', 'James', 'Michener', NULL, NULL),
  ('The Novel', 'James', 'Michener', NULL, NULL),
  ('The Source', 'James', 'Michener', NULL, NULL),
  ('Tokyo Ueno Sta on', 'Yu', 'Miri', NULL, NULL),
  ('A Place for Us', 'Fa ma Farheen', 'Mirza', NULL, NULL),
  ('The Ta ooist of Auschwitz', 'Heather', 'Morris', NULL, NULL),
  ('The Vault', 'Boyd', 'Morrison', NULL, NULL),
  ('The Roswell Conspiracy', 'Boyd', 'Morrison', NULL, NULL),
  ('The Ark', 'Boyd', 'Morrison', NULL, NULL),
  ('Beloved', 'Toni', 'Morrison', NULL, NULL),
  ('Gone Fishin', 'Walter', 'Mosely', NULL, NULL),
  ('The Long Fall (Leonid McGill)', 'Walter', 'Mosely', NULL, NULL),
  ('When The Thrill Is Gone (Leonid McGill)', 'Walter', 'Mosely', NULL, NULL),
  ('Known to Evil (Leonid McGill)', 'Walter', 'Mosely', NULL, NULL),
  ('All I Did Was Shoot My Man (Leonid McGill)', 'Walter', 'Mosely', NULL, NULL),
  ('The Last Days of Ptolemy Grey', 'Walter', 'Mosely', NULL, NULL),
  ('And Some mes I Wonder About You (Leonid McGill)', 'Walter', 'Mosely', NULL, NULL),
  ('Trouble is What I Do (Leonid McGill)', 'Walter', 'Mosely', NULL, NULL),
  ('Always Outnumbered', 'Walter', 'Mosely', NULL, NULL),
  ('Walkin'' the Dog', 'Walter', 'Mosely', NULL, NULL),
  ('Down the River Unto the Sea (King Oliver)', 'Walter', 'Mosely', NULL, NULL),
  ('The Awkward Blackman (short stories)', 'Walter', 'Mosely', NULL, NULL),
  ('Every Man a King (King Oliver)', 'Walter', 'Mosely', NULL, NULL),
  ('Touched', 'Walter', 'Mosely', NULL, NULL),
  ('Been Wrong So Long It Feels Like Right (King Oliver)', 'Walter', 'Mosely', NULL, NULL),
  ('Hello Beau ful', 'Ann', 'Napolitano', NULL, NULL),
  ('Sanctuary', 'Heidi', 'Neumark', NULL, NULL),
  ('A Calculated Risk', 'Katherine', 'Neville', NULL, NULL),
  ('The Eight', 'Katherine', 'Neville', NULL, NULL),
  ('The Fire', 'Katherine', 'Neville', NULL, NULL),
  ('Everything I Never Told You', 'Celeste', 'Ng', NULL, NULL),
  ('Li le Fires Everywhere', 'Celeste', 'Ng', NULL, NULL),
  ('Our Missing Hearts', 'Celeste', 'Ng', NULL, NULL),
  ('Killing Kennedy', 'Bill', 'O''Reilly', NULL, NULL),
  ('1984', 'George', 'Orwell', NULL, NULL),
  ('Animal Farm', 'George', 'Orwell', NULL, NULL),
  ('The Thursday Murder Club', 'Richard', 'Osman', NULL, NULL),
  ('No Easy Day', 'Mark', 'Owen', NULL, NULL),
  ('Where the Crawdads Sing', 'Delia', 'Owens', NULL, NULL),
  ('To Sleep in a Sea of Stars', 'Christopher', 'Paolini', NULL, NULL),
  ('Cry, TheBeloved Country', 'Alan', 'Paton', NULL, NULL),
  ('Kiss the Girls', 'James', 'Pa erson', NULL, NULL),
  ('Valient Ambi on', 'Nathaniel', 'Philbrick', NULL, NULL),
  ('The Chosen', 'Chaim', 'Potok', NULL, NULL),
  ('The Promise', 'Chaim', 'Potok', NULL, NULL),
  ('Impact', 'Douglas', 'Preston', NULL, NULL),
  ('The Monster of Florence (with Mario Spezi)', 'Douglas', 'Preston', NULL, NULL),
  ('The Five Wounds', 'Kirs n Valdez', 'Quade', NULL, NULL),
  ('Black and Blue', 'Anna', 'Quindlin', NULL, NULL),
  ('Blessings', 'Anna', 'Quindlin', NULL, NULL),
  ('Living Out Loud', 'Anna', 'Quindlin', NULL, NULL),
  ('One True Thing', 'Anna', 'Quindlin', NULL, NULL),
  ('Thinking Out Loud', 'Anna', 'Quindlin', NULL, NULL),
  ('Aletrnate Side', 'Anna', 'Quindlin', NULL, NULL),
  ('The 500', 'Ma hew', 'Quirk', NULL, NULL),
  ('The Direc ve', 'Ma hew', 'Quirk', NULL, NULL),
  ('The Celes ne Prophency', 'James', 'Red eld', NULL, NULL),
  ('New York 2140', 'Kim Stanley', 'Robinson', NULL, NULL),
  ('Divergent', 'Veronica', 'Roth', NULL, NULL),
  ('Insurgent', 'Veronica', 'Roth', NULL, NULL),
  ('Allegiant', 'Veronica', 'Roth', NULL, NULL),
  ('Harry Po er and the Chamber of Secrets', 'J.K.', 'Rowling', NULL, NULL),
  ('Harry Po er and the Deathly Hallows', 'J.K.', 'Rowling', NULL, NULL),
  ('Harry Po er and the Goblet of Fire', 'J.K.', 'Rowling', NULL, NULL),
  ('Harry Po er and the Half-Blood Prince', 'J.K.', 'Rowling', NULL, NULL),
  ('Harry Po er and the Order of the Phoenix', 'J.K.', 'Rowling', NULL, NULL),
  ('Harry Po er and the Prisoner of Azkaban', 'J.K.', 'Rowling', NULL, NULL),
  ('Harry Po er and the Sorcerer''s Stone', 'J.K.', 'Rowling', NULL, NULL),
  ('Victory City', 'Salman', 'Rushdie', NULL, NULL),
  ('Rising Out of Hatred', 'Eli', 'Saslow', NULL, NULL),
  ('The Killer Angels', 'Michael', 'Shaara', NULL, NULL),
  ('Saint X', 'Alexis', 'Shaitken', NULL, NULL),
  ('Elsewhere', 'Alexis', 'Shaitken', NULL, NULL),
  ('Phase Six', 'Jim', 'Shepard', NULL, NULL),
  ('Hidden Figures', 'Margot Lee', 'She erly', NULL, NULL),
  ('The Rise and Fall of the Third Reich', 'William', 'Shier', NULL, NULL),
  ('Gorky Park', 'Mar n Cruz', 'Smith', NULL, NULL),
  ('One Day in the Life of Ivan Denisovich', 'Alexander', 'Solzhenitsyn', NULL, NULL),
  ('The Hour of Peril', 'Daniel', 'Stashower', NULL, NULL),
  ('East of Eden', 'John', 'Steinbeck', NULL, NULL),
  ('Grapes of Wrath', 'John', 'Steinbeck', NULL, NULL),
  ('In ux', 'Daniel', 'Suarez', NULL, NULL),
  ('Daemon', 'Daniel', 'Suarez', NULL, NULL),
  ('Freedom', 'Daniel', 'Suarez', NULL, NULL),
  ('Kill Decision', 'Daniel', 'Suarez', NULL, NULL),
  ('Gulliver''s Travels', 'Jonathon', 'Swi', NULL, NULL),
  ('One Rough Man', 'Brad', 'Taylor', 'Pike Logan', '1'),
  ('All Necessary Force', 'Brad', 'Taylor', 'Pike Logan', '2'),
  ('Enemy of Mine', 'Brad', 'Taylor', 'Pike Logan', '3'),
  ('The Widow''s Strike', 'Brad', 'Taylor', 'Pike Logan', '4'),
  ('The Polaris Protocol', 'Brad', 'Taylor', 'Pike Logan', '5'),
  ('Days of Rage', 'Brad', 'Taylor', 'Pike Logan', '6'),
  ('No Fortunate Son', 'Brad', 'Taylor', 'Pike Logan', '7'),
  ('Hunter Killer', 'Brad', 'Taylor', 'Pike Logan', '8'),
  ('American Traitor', 'Brad', 'Taylor', 'Pike Logan', '9'),
  ('The Devil''s Ransom', 'Brad', 'Taylor', 'Pike Logan', '10'),
  ('The Lions of Lucerne', 'Brad', 'Thor', 'Sco Horvath', '1'),
  ('Path of the Assassin', 'Brad', 'Thor', 'Sco Horvath', '2'),
  ('State of the Union', 'Brad', 'Thor', 'Sco Horvath', '3'),
  ('Blowback', 'Brad', 'Thor', 'Sco Horvath', '4'),
  ('Takedown', 'Brad', 'Thor', 'Sco Horvath', '5'),
  ('The First Commandment', 'Brad', 'Thor', 'Sco Horvath', '6'),
  ('The Last Patriot', 'Brad', 'Thor', 'Sco Horvath', '7'),
  ('The Apostle', 'Brad', 'Thor', 'Sco Horvath', '8'),
  ('Foreign Agent', 'Brad', 'Thor', 'Sco Horvath', '15'),
  ('Use of Force', 'Brad', 'Thor', 'Sco Horvath', '16'),
  ('Spy Master', 'Brad', 'Thor', 'Sco Horvath', '17'),
  ('Backlash', 'Brad', 'Thor', 'Sco Horvath', '18'),
  ('Near Dark', 'Brad', 'Thor', 'Sco Horvath', '19'),
  ('Black Ice', 'Brad', 'Thor', 'Sco Horvath', '20'),
  ('Rising Tiger', 'Brad', 'Thor', 'Sco Horvath', '21'),
  ('Dead Fall', 'Brad', 'Thor', 'Sco Horvath', '22'),
  ('Shadow of Doubt', 'Brad', 'Thor', 'Sco Horvath', '23'),
  ('Edge of Honor', 'Brad', 'Thor', 'Sco Horvath', '24'),
  ('The Fellowship of the Ring', 'J. R. R.', 'Tolkien', NULL, NULL),
  ('The Hobbit', 'J. R. R.', 'Tolkien', NULL, NULL),
  ('The Return of the King', 'J. R. R.', 'Tolkien', NULL, NULL),
  ('The Two Towers', 'J. R. R.', 'Tolkien', NULL, NULL),
  ('War and Peace', 'Leo', 'Tolstoy', NULL, NULL),
  ('A Gentleman in Moscow', 'Amor', 'Towles', NULL, NULL),
  ('The Guns of August', 'Barbara', 'Tuchmann', NULL, NULL),
  ('Presumed Innocent', 'Sco', 'Turow', NULL, NULL),
  ('The Last Trial', 'Sco', 'Turow', NULL, NULL),
  ('Huckleberry Finn', 'Mark', 'Twain', NULL, NULL),
  ('Armageddon', 'Leon', 'Uris', NULL, NULL),
  ('Exodus', 'Leon', 'Uris', NULL, NULL),
  ('Mila 18', 'Leon', 'Uris', NULL, NULL),
  ('QB VII', 'Leon', 'Uris', NULL, NULL),
  ('Redemption', 'Leon', 'Uris', NULL, NULL),
  ('The Haj', 'Leon', 'Uris', NULL, NULL),
  ('Topaz', 'Leon', 'Uris', NULL, NULL),
  ('Trinity', 'Leon', 'Uris', NULL, NULL),
  ('Countdown 1945', 'Chris', 'Wallace', NULL, NULL),
  ('The Reunion', 'Dan', 'Walsh', NULL, NULL),
  ('All the Kings Men', 'Robert Penn', 'Warren', NULL, NULL),
  ('Project Hail Mary', 'Andy', 'Weir', NULL, NULL),
  ('Artemis', 'Andy', 'Weir', NULL, NULL),
  ('Harlem Shuffle', 'Colson', 'Whitehead', NULL, NULL),
  ('The Power of the Dog', 'Don', 'Winslow', NULL, NULL),
  ('Master Slave Husband Wife', 'Ilyon', 'Woo', NULL, NULL),
  ('Orchid Beach', 'Stuart', 'Woods', NULL, NULL),
  ('Two Dollar Bill', 'Stuart', 'Woods', NULL, NULL),
  ('Thief of Dreams', 'John', 'Yount', NULL, NULL)
ON CONFLICT (title, author_last) DO NOTHING;

SELECT COUNT(*) as total_books FROM books;